### ISSUE TITLE
Support latest gitversion

### ISSUE THREAD

**Issue by NecatiMeral** [4tecture/BuildVersioning#20]
As far as I can tell, the major differences are:

* gitversion now runs on `netcoreapp3.1` (probably `net5` soon)
* gitversion executable name has been changed from `GitVersion.exe` to `gitversion.exe`

**Comment by knoxi** [comment]
@NecatiMeral, have a look at the latest version of BuildVersioning.
We are now supporting the latest version of GitVersion for Windows and Linux agents.

**Comment by NecatiMeral** [comment]
Thanks for the head up. I've already noticed that our devops instance updated the extension (and broke our builds 😄 ).
I had to manually add the `UseDotnet` task with runtime 2.1.0 to make the versioning task work again. Added it to a template and got rid of the issue. I'll check this out as soon as I can.

EDIT: Are there any changelogs available for this task?

**Comment by NecatiMeral** [comment]
Issue is resolved. Latest gitversion can used properly (just make sure you install NET5.0 runtime first):

```
- task: UseDotNet@2
  displayName: 'Install Dependencies'
  inputs:
    packageType: 'runtime'
    version: '5.x'
- task: BuildVersioning@0
  displayName: 'Build Versioning'
  inputs:
    doInstallGitVersion: true
    GitVersionInstallerVersion: '5.6.6'
    doUseLatestGitVersionInstallerVersion: false
```
