### ISSUE TITLE
Ambiguous `VersionCode` for prereleases

### ISSUE THREAD

**Issue by NecatiMeral** [4tecture/BuildVersioning#22]
Hi,

first of all I gotta thank you for this extension. It really helps versioning by a lot!

While building a CI/CD Pipeline for a android application, I noticed the undocumented `BuildVersion.VersionCode` variable which is exactly what I'm looking for.

Unfortunately, the version code is only raised by updating the patch version at least.
Is there a configuration value to make the version code depending on pre-releases?

Example:
VersionCode for `1.0.0-alpha0002` should be higher than the version code for release `1.0.0-alpha0001`.

Thanks in advance.

## Configuration

My versioning template looks like this:

```yaml
steps:
- task: UseDotNet@2
  displayName: 'Install Dependencies'
  inputs:
    packageType: 'sdk'
    version: '5.x'

- task: BuildVersioning@0
  name: BuildVersioning
  displayName: 'Build Versioning'
  inputs:
    versionSource: 'gitversion'
    doInstallGitVersion: true
    GitVersionInstallerVersion: '5.6.10'
    doUseLatestGitVersionInstallerVersion: false
    GitVersionToolInstallation: 'global'
    paramAssemblyVersion: '7'
    paramAssemblyFileVersion: '7'
    paramAssemblyInformationalVersion: '6'
    paramOverwriteFourthDigitWithBuildCounter: true
    paramVersionCode: '2'
    doAssemblyInfoAppendSuffix: false
    doConvertAssemblyInfoToLowerCase: false
    buildNumberVersionFormat: '3'
    buildNumberAction: 'replace'
    doReplaceAssemblyInfo: false
    doReplaceNuspec: false
    doReplaceNpm: false
    doReplaceDotNetCore: false
    filePatternDotNetCore: |
      **\*.csproj
      **\*.props
    paramDotNetCoreVersionType: '3'
    doReplaceAndroid: false
    doReplaceiOS: false
    doReplaceCustom: false
    doShowWarningsForUnmatchedRegex: false
    excludeFilePattern: |
      !**/bin/**
      !**/obj/**
      !**/node_modules/**
```

I am just using the buildversioning to calculate the required values. I'm updating the `AndroidManifest.xml` manually:

```yaml
  - task: android-manifest-version@1
    displayName: Update Manifest (Version)
    inputs:
      sourcePath: 'MyPath/AndroidManifest.xml'
      versionCodeOption: 'buildid'
      versionCode: '$(BuildVersion.VersionCode)'
      versionName: '$(BuildVersion.VersionInfo)'
      printFile: true
```
