### ISSUE TITLE
GitVersion V6 Release causes unexpected behaviour

### ISSUE THREAD

**Issue by noppert-cede** [4tecture/BuildVersioning#27]
Since yesterdays official release of gitversion V6.0.0, most of our azure pipelines aren't working anymore.

While some issues could be fixed by making changes to our GitVersion.yml, it seems that the Build.BuildNumber inside of the Azure-Pipelines is not updated anymore, which causes several following steps to fail.

By replacing the Build Versioning step provided by you guys it was possible to get gitversion back to work, but since we do not know what else might happen behind the curtain, we can't be sure if other processes especially in the Context of Helm will cause problems as well.

hier ein Auszug wie gitversion aktuell funktioniert mit V6:
```
steps:
- checkout: self
  fetchDepth: 0

- task: gitversion/setup@2
  displayName: Install GitVersion
  inputs:
    versionSpec: '6.x'

- task: gitversion/execute@2
  displayName: Determine Version
```
